openapi: 3.0.0
info:
  title: api
  version: '1.0'
  description: 'Click [here](../docs/anchors.md#header1) or [here](../docs/anchors.md#header3)'
servers:
  - url: 'http://localhost:3000'
paths:
  /api:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  raz:
                    type: string
                  dwa:
                    type: string
                  trzy:
                    type: string
      operationId: get-api
      parameters:
        - schema:
            type: string
            default: aaa
            enum:
              - api
          in: query
          deprecated: true
          name: oa
          explode: true
          allowEmptyValue: true
          allowReserved: true
      description: ''
components:
  schemas: {}
