openapi: 3.0.0
info:
  title: api
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /api:
    get:
      summary: Your GET endpoint
      tags: []
      responses: {}
      operationId: get-api
      parameters:
        - schema:
            type: string
            deprecated: true
            default: aaa
            enum:
              - api
          in: query
          name: a
          explode: true
          allowEmptyValue: true
          allowReserved: true
components:
  schemas: {}
