openapi: 3.0.0
info:
  title: api
  version: '1.0'
  description: 'Click [here](../docs/anchors.md#header1) or [here](../docs/anchors.md#header3)'
servers:
  - url: 'http://localhost:3000'
paths:
  /api:
    get:
      summary: Your GET endpoint
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  raz:
                    type: string
                  dwa:
                    type: string
                  trzy:
                    type: string
      operationId: get-api
      parameters:
        - schema:
            type: string
            default: aaa
            enum:
              - api
          in: query
          deprecated: true
          name: a
          explode: true
          allowEmptyValue: true
          allowReserved: true
      description: ''
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                '':
                  type: string
components:
  schemas:
    Kle:
      title: Kle
      type: object
      properties:
        id:
          type: string
tags: []
