swagger: '2.0'
info:
  title: oas2
  version: '1.0'
host: 'localhost:3000'
schemes:
  - http
produces:
  - application/json
consumes:
  - application/json
paths:
  /oas2:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          schema:
            type: object
            properties:
              a:
                type: string
            example:
              type: default schema
            x-examples:
              ex-1:
                type: named schema
              ex-2:
                type: named schema-2
      operationId: get-oas2
      parameters:
        - in: body
          name: body
          schema:
            type: object
            properties:
              a:
                type: string
            example:
              type: default schema
            x-examples:
              ex-1:
                type: named schema
              ex-2:
                type: named schema-2
definitions: {}
